<?php

return array(
    0 =>
        array(
            'name'    => 'language',
            'title'   => '语言',
            'type'    => 'select',
            'content' =>
                array(
                    'en'        => '英语（美国）',
                    'af_ZA'     => '南非荷兰语（南非）',
                    'ar'        => '阿拉伯',
                    'eu'        => '巴斯克',
                    'be'        => '白俄罗斯',
                    'bg_BG'     => '保加利亚语（保加利亚）',
                    'ca'        => '加泰罗尼亚',
                    'zh_CN'     => '简体中文',
                    'zh_TW'     => '繁体中文',
                    'hr'        => '克罗地亚	',
                    'cs'        => '捷克',
                    'da'        => '丹麦',
                    'dv'        => '迪维希',
                    'nl'        => '荷兰',
                    'en_CA'     => '英语（加拿大)',
                    'en_GB'     => '英语（英国）',
                    'et'        => '爱沙尼亚语',
                    'fr_FR'     => '法语（法国）',
                    'gl'        => '加利西亚',
                    'ka_GE'     => '格鲁吉亚（格鲁吉亚）',
                    'de'        => '德语',
                    'de_AT'     => '德语（奥地利）',
                    'el'        => '希腊语',
                    'he_IL'     => '希伯来语（以色列）',
                    'hu_HU'     => '	匈牙利语（匈牙利语）',
                    'ga'        => '爱尔兰',
                    'it'        => '意大利',
                    'ja'        => '日本',
                    'kab'       => '卡拜尔',
                    'kk'        => '哈萨克人',
                    'km_KH'     => '高棉（柬埔寨）',
                    'ko_KR'     => '韩国（韩国）',
                    'lv'        => '拉脱维亚',
                    'nb_NO	' => '挪威博克马尔（挪威）',
                    'fa_IR'     => '波斯（伊朗）',
                    'pl'        => '抛光',
                    'pt_BR'     => '葡萄牙语（巴西）',
                    'pt_PT'     => '	葡萄牙（葡萄牙）',
                    'ro'        => '罗马尼亚',
                    'ru'        => '俄语',
                    'sk'        => '斯洛伐克',
                    'sl_SI'     => '斯洛维尼亚语（斯洛文尼亚）',
                    'es'        => '西班牙语',
                    'es_MX'     => '西班牙（墨西哥）',
                    'sv_SE'     => '	瑞典语（瑞典）',
                    'ta'        => '	泰米尔人',
                    'ta_IN'     => '泰米尔（印度）',
                    'th_TH'     => '泰国（泰国）',
                    'tr'        => '土耳其',
                    'tr_TR'     => '土耳其（土耳其）',
                    'uk'        => '乌克兰',
                    'uk_UA'     => '乌克兰（乌克兰）',
                    'uz'        => '乌兹别克',
                    'vi_VN'     => '越南语（越南）',
                    'cy'        => '威尔士语',
                ),
            'value'   => 'zh_CN',
            'rule'    => 'required',
            'msg'     => '必须选择语言',
            'tip'     => '选择语言包',
            'ok'      => '',
            'extend'  => '',
        ),
    1 =>
        array(
            'name'    => 'plugins',
            'title'   => '自定义插件',
            'type'    => 'selects',
            'content' =>
                array(
                    'autolink'     => '自动创建超链接',
                    'autosave'     => '自动保存',
                    'print'        => '打印',
                    'preview'      => '预览',
                    'spellchecker' => '拼写检查',
                    'fullscreen'   => '全屏',
                    'media'        => '媒体',
                    'emoticons'    => '表情',
                    'template'     => '模板',
                    'paste'        => '粘贴',
                    'textcolor'    => '文字颜色',
                ),
            'value'   => 'autolink,autosave,print,preview,spellchecker,fullscreen,media,emoticons,template,paste,textcolor',
            'rule'    => '',
            'msg'     => '',
            'tip'     => '自主选择插件',
            'ok'      => '',
            'extend'  => '',
        ),
    2 =>
        array(
            'name'    => 'toolbar',
            'title'   => '快捷工具栏',
            'type'    => 'radio',
            'content' =>
                array(
                    1 => '显示',
                    0 => '不显示',
                ),
            'value'   => '1',
            'rule'    => '',
            'msg'     => '',
            'tip'     => '',
            'ok'      => '',
            'extend'  => '',
        ),
    3 =>
        array(
            'name'    => 'subDom',
            'title'   => '所在表单提交dom',
            'type'    => 'string',
            'content' =>
                array(),
            'value'   => ':button[type=submit],input[type=submit]',
            'rule'    => 'required',
            'msg'     => '',
            'tip'     => '多个用,隔开:button[type=submit]为默认的请不要删除',
            'ok'      => '',
            'extend'  => '',
        ),
);
